import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";
import { Menu } from "@/components/Menu/Menu";
import Layout from "@/pages/layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Menu />
        <h1>Home</h1>
        <h2>
          <Link href="/">← Back to home</Link>
        </h2>
      </div>
    </>
  );
}
